### ISSUE TITLE
Fix DPad interface to work diagonally

### ISSUE THREAD

**Issue by kevinfrei** [technototes/SkyStone2019#5]

**Comment by 1198159** [comment]
I think this is done, but needs testing
@sgeigerk or @kevinfrei, if you are reading this, tell me if it is done.

**Comment by kevinfrei** [comment]
@sgeigerk has to change the dpad.isUp/isDown/isLeft/isRight to ignore the orthogonal axis values (and maybe add dpad.isOnlyUp/isOnlyDown/isOnlyLeft/isOnlyRight if we want those...) She was working on it  today, but I don't know what state it was in.

**Comment by kevinfrei** [comment]
Validated that @sgeigerk got it fixed. Closing.
